# Generated by Django 4.2.23 on 2025-09-01 13:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='RFID card UID', max_length=64, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current card balance in pesos', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated'), ('lost', 'Lost')], default='active', help_text='Current card status', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this card', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFID Card',
                'verbose_name_plural': 'RFID Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('purchase', 'Purchase'), ('ride', 'Ride'), ('reload', 'Reload'), ('deactivate', 'Deactivate'), ('lost', 'Lost'), ('reactivate', 'Reactivate')], help_text='Type of transaction', max_length=12)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Transaction amount (positive value)', max_digits=10, null=True)),
                ('direction', models.CharField(blank=True, choices=[('credit', 'Credit'), ('debit', 'Debit'), ('neutral', 'Neutral')], help_text='Transaction direction', max_length=7, null=True)),
                ('note', models.TextField(blank=True, help_text='Additional notes about the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(help_text='Associated RFID card', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='cards.card')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
