# Generated by Django 4.2.23 on 2025-09-01 16:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Station name', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Station code', max_length=10, unique=True)),
                ('ride_cost', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Ride cost from this station in pesos', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this station is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Train Station',
                'verbose_name_plural': 'Train Stations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='station',
            field=models.ForeignKey(blank=True, help_text='Station where transaction occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.trainstation'),
        ),
    ]
