# Generated by Django 4.2.23 on 2025-09-01 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_trainstation_transaction_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Passenger's first name", max_length=50)),
                ('last_name', models.CharField(help_text="Passenger's last name", max_length=50)),
                ('email', models.EmailField(blank=True, help_text="Passenger's email address", max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text="Passenger's phone number", max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text="Passenger's date of birth", null=True)),
                ('address', models.TextField(blank=True, help_text="Passenger's address", null=True)),
                ('emergency_contact', models.CharField(blank=True, help_text='Emergency contact person', max_length=100, null=True)),
                ('emergency_phone', models.CharField(blank=True, help_text='Emergency contact phone', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this passenger is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='passenger',
            field=models.ForeignKey(blank=True, help_text='Associated passenger (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.passenger'),
        ),
    ]
