# Generated by Django 4.2.23 on 2025-09-01 16:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_passenger_card_passenger'),
    ]

    operations = [
        migrations.CreateModel(
            name='FareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('regular', 'Regular'), ('student', 'Student'), ('senior', 'Senior')], help_text='Fare category name', max_length=20, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage (0.00 = no discount, 20.00 = 20% discount)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is active')),
                ('description', models.TextField(blank=True, help_text='Description of the category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fare Category',
                'verbose_name_plural': 'Fare Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='card',
            name='fare_category',
            field=models.ForeignKey(blank=True, default=None, help_text='Fare category for discounts', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.farecategory'),
        ),
    ]
