# Generated by Django 4.2.23 on 2025-09-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_farecategory_card_fare_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='passenger_email',
            field=models.EmailField(blank=True, help_text='Passenger email (for quick card purchase)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='passenger_name',
            field=models.CharField(blank=True, help_text='Passenger name (for quick card purchase)', max_length=100, null=True),
        ),
    ]
