# Generated by Django 4.2.23 on 2025-09-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_card_passenger_email_card_passenger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='passenger_email',
            field=models.EmailField(help_text='Passenger email (required for card purchase)', max_length=254),
        ),
        migrations.AlterField(
            model_name='card',
            name='passenger_name',
            field=models.CharField(help_text='Passenger name (required for card purchase)', max_length=100),
        ),
    ]
