# Generated by Django 4.2.23 on 2025-09-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_alter_card_passenger_email_alter_card_passenger_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farecategory',
            name='name',
            field=models.CharField(choices=[('regular', 'Regular'), ('student', 'Student'), ('senior', 'Senior'), ('pwd', 'PWD (Person with Disability)')], help_text='Fare category name', max_length=20, unique=True),
        ),
    ]
